name: just_breathe
description: A simple mediation app

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.6
  google_fonts: ^6.1.0
  styled_widget: ^0.4.1
  #url_launcher: ^6.2.1
  responsive_framework: ^1.1.1
  assets_audio_player: ^3.1.1
  tinycolor2: ^3.0.1
  copy_with_extension: ^5.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  intl_translation: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4



flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - google_fonts/
flutter_intl:
  enabled: true
