name: just_breathe
description: A simple mediation app

version: 1.0.0+3

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.3
  google_fonts: ^6.2.1
  styled_widget: ^0.4.1
  url_launcher: ^6.3.1
  responsive_framework: ^1.5.1
  just_audio: ^0.9.41
  tinycolor2: ^3.0.1
  copy_with_extension: ^5.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_translation: ^0.20.0

dependency_overrides:
  win32: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  copy_with_extension_gen: ^5.0.4



flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - google_fonts/
flutter_intl:
  enabled: true
